[build]
  functions = "netlify/functions"
  publish = "public"
  command = "echo 'Static site - no build required'"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/health"
  to = "/.netlify/functions/health"
  status = 200

[[redirects]]
  from = "/chat"
  to = "/.netlify/functions/chat"
  status = 200

[[redirects]]
  from = "/test"
  to = "/.netlify/functions/test"
  status = 200

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--production=false"
